apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset
  labels:
    app: httpd_app
    type: front-end
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd-replicaset
  template:
    metadata:
      name: httpd-replicaset
      labels:
        app: httpd-replicaset
    spec:
      containers:
        - name: httpd-container
          image: httpd:latest